table Customers
	lineageTag: d767a4aa-7d95-42be-b55d-c36e850106df

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 451fe94e-c31b-426d-a84b-f19e4d4f7eaa
		summarizeBy: count
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: daa3d81e-de5c-4f90-bcda-a7e407afdaec
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 816c4892-7006-478e-a9cc-49dc6bcaa0c6
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 28b8bd5d-196f-4596-be33-f8399992d79a
		summarizeBy: none
		sourceColumn: BirthDate

		variation Variation
			isDefault
			relationship: f7360717-3993-4cea-87f7-8fa149b832d5
			defaultHierarchy: LocalDateTable_49cc0b43-02c8-4fac-9f8f-0c8c71be854f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Membership Start Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: d548d3d5-fb89-4567-a83f-45c52667c6bf
		summarizeBy: none
		sourceColumn: Membership Start Date

		variation Variation
			isDefault
			relationship: 615c63ea-dcc1-4361-a81e-9ff905becb67
			defaultHierarchy: LocalDateTable_1e7e5cb1-b0a9-4531-a10e-94dfba51f91e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Purchase Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: c7a0875f-f963-4101-bd24-27de0affef2c
		summarizeBy: none
		sourceColumn: Last Purchase Date

		variation Variation
			isDefault
			relationship: 19aee497-7c12-494b-ba21-a2e294b79a37
			defaultHierarchy: LocalDateTable_c3bc4e09-e0b9-4b9c-b59e-7b84c9893e46.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Birth Year' = Year(Customers[BirthDate])
		dataType: int64
		formatString: 0
		lineageTag: 43f50206-74b3-43e3-b7e2-8c7f0a1a0969
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Birth Month' = ```
			Month(Customers[BirthDate]) 
			```
		dataType: int64
		formatString: 0
		lineageTag: 9d443652-75d6-4855-8e6c-bb948092c10a
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Birth Day' = ```
			Day(Customers[BirthDate]) 
			```
		dataType: int64
		formatString: 0
		lineageTag: 4bde8337-c860-439a-91a7-12b956859f40
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'WEEK DAY' = WEEKDAY(Customers[BirthDate])
		dataType: int64
		formatString: 0
		lineageTag: 2fb6eb4a-b0d3-472e-b448-f84d01ee0bed
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column WEEKNUM = ```
			WEEKNUM(Customers[BirthDate]) 
			```
		dataType: int64
		formatString: 0
		lineageTag: 7ddf4949-2dab-40f9-9105-1dc4f9572014
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'MONTH NAME' = Customers[BirthDate].[Month]
		dataType: string
		lineageTag: a7ba63e7-9b7a-4999-9745-1487b24f6a06
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column QUARTER = Customers[BirthDate].[Quarter]
		dataType: string
		lineageTag: 0019578b-0ea4-4eca-a072-ac8f6415a838
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'FORMATTED DATE' = FORMAT(Customers[BirthDate],"HH MM DD/MMMM/YY")
		dataType: string
		lineageTag: 767062bb-d568-4145-b82f-77f01ce39ac8
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'TODAY''S DATE' = ```
			TODAY() 
			```
		dataType: dateTime
		formatString: General Date
		lineageTag: c1d25d97-d7bb-435f-911c-97eb1bda1ec1
		summarizeBy: none
		isDataTypeInferred

		variation Variation
			isDefault
			relationship: dc56f999-5cf1-4c93-bb04-5f650de8dc63
			defaultHierarchy: LocalDateTable_4bd55254-3142-4270-86e7-13260d4b6a70.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'NOW DATE' = ```
			NOW() 
			```
		dataType: dateTime
		formatString: General Date
		lineageTag: 756baa9b-cbd8-4b5c-bbd0-4ffe788275d9
		summarizeBy: none
		isDataTypeInferred

		variation Variation
			isDefault
			relationship: 28551a98-986c-4aa0-a21e-ed4b98b7e021
			defaultHierarchy: LocalDateTable_8717fed2-129e-47c4-9829-6494efbab71c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column AGE = YEAR(TODAY()) - Customers[Birth Year]
		dataType: int64
		formatString: 0
		lineageTag: cdd28c3b-ce3d-43d5-9bc8-dd898b3d68cc
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition Customers = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Saba Teferra\Downloads\Date Time.xlsx"), null, true),
				    Customers_Sheet = Source{[Item="Customers",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Customers_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerID", Int64.Type}, {"FirstName", type text}, {"LastName", type text}, {"BirthDate", type datetime}, {"Membership Start Date", type datetime}, {"Last Purchase Date", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

