table Returns
	lineageTag: 5dc70386-340d-4f6a-b01e-7d3c65bb18f2

	column 'Order ID'
		dataType: int64
		formatString: 0
		lineageTag: d4927f0f-2fe7-4f50-b29b-d3dab0514aa7
		summarizeBy: count
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 2589b00c-e726-4649-9e70-977580b8913e
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition Returns = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Saba Teferra\Downloads\Sample Superstore (1).xlsx"), null, true),
				    Returns_Sheet = Source{[Item="Returns",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Returns_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order ID", Int64.Type}, {"Status", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

