table Users
	lineageTag: f444d818-5553-4857-963e-296198831ea5

	column Column1
		dataType: string
		lineageTag: a0f0726f-43d4-4eb3-aa2b-69a3b1f97e91
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 9491c929-a0a7-401c-b8ce-ed21fc41cc31
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition Users = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Saba Teferra\Downloads\Sample Superstore (1).xlsx"), null, true),
				    Users_Sheet = Source{[Item="Users",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Users_Sheet,{{"Column1", type text}, {"Column2", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

